### PR TITLE
assets/textures/potions/StrengthPotion.png

### PR DESCRIPTION
**Pull request by kyryllparolys**
strengthpotionbottle

### CODE REVIEW

**Comment by rzats** [comment]
The pull request has to include two files:

- The potion's texture (you have this in the PR's description)
- The potion's prefab (you seem to have this in a different branch of your fork: https://github.com/kiruxaker/Potions/tree/patch-2)

Can you create a different PR with these two files (and nothing else)?

**Comment by kyryllparolys** [comment]
Eemm, can I create minor regen potion??
Plz answer as fast as you can😄😄

4 дек. 2016 г. 20:33 пользователь "Rostyslav Zatserkovnyi" <
notifications@github.com> написал:

**Comment by rzats** [comment]
We already have a regen potion, but a new "lesser" version is still OK :slightly_smiling_face:

**Comment by kyryllparolys** [comment]
I'm really sorry, but can you help me with git I really can't get how to
pull this request((

5 дек. 2016 г. 17:07 пользователь "Rostyslav Zatserkovnyi" <
notifications@github.com> написал:

**Comment by rzats** [comment]
Short version: purge your workspace/fork and create another pull request. This is by far the easiest way to resolve any git issues 🙂 

Longer version:

- **Back up the files (texture and prefab) that you've created**
- Delete the module folder on your PC
- Delete your fork (https://github.com/kiruxaker/Potions)
- Create a new fork
- `git clone https://github.com/kiruxaker/Potions.git`
- Navigate to the folder that was created
- `git checkout -b feature-additional-potions`
- Paste the texture and prefab files into the folders they should be in
- `git add -A`
- `git commit -m "Add additional potions"`
- `git push origin feature-additional-potions`
- Create a new pull request
- Done! ✔️

**Pull request closed without merging**
