### PR TITLE
Add VulnerabilityPoison.prefab and VulnerabilityPoisonBottle.png

### PR DESCRIPTION
**Pull request by SarahMcDougald**
I noticed that in the module, there is a "buff" potion, Resist Physical, that grants temporary additional defense, but no poison that lowers defense! So, I added a new prefab potion called Vulnerability Poison (VulnerabilityPoison.prefab), and I made a new image for it by modifying the base image provided in the module (VulnerabilityPoisonBottle.png). The effect of the new potion is to decrease the defense of the user by 10, lasting for 30 seconds.

To test: 

- Open a new game
- Open the console
- use the 'give' command to produce the new potion

### CODE REVIEW

**Comment by smsunarto** [comment]
Hey @SarahMcDougald, thanks for the PR.

Currently we don't have any potion effects called `VULNERABLE_PHYSICAL` because of that, this potion will not do anything. If you want the potion to have effect you should add the code also instead of just the item files.

Secondly, I don't think that the name should be "VulnerabilityPoison" because we have potion that is _actually_ poison and this might confuses user.

Check: https://github.com/Terasology/Potions/blob/master/src/main/java/org/terasology/potions/PotionCommonEffects.java for more reference regarding effects that currently exist.

**Comment by xrtariq2594** [comment]
@smsunarto Hmm, in that case, what should the potion be named then? AntiResistPhysical? WeakenResistPhysical? Another name?

**Comment by smsunarto** [comment]
@xrtariq2594 perhaps DefenseBreakPotion,  DefenseReductionPotion, or any creative name I suppose (should probably have fantasy-ish theme to it). Potion name doesnt need to be intuitive, as long it sorta make sense I think it's fine since we can just depend on the tooltip for explanation

**Comment by xrtariq2594** [comment]
In that case @smsunarto, I suppose DefenseBreakPotion would be for `physical` attacks, and something like PoisonDefenseBreakPotion would be for `poison` attacks.

**Comment by SarahMcDougald** [comment]
@smsunarto Okay, thank you for the clarification! One question: would the new effect VULNERABLE_PHYSICAL (or whatever it will be named) only need to be added to the PotionCommonEffects class? Because if other code alterations are needed when adding a new effect, it would be much easier to use the already existing RESIST_PHYSICAL effect and have a negative multiplier (i.e. -10). 

And you're right, the name could be more clear. I think I'll go with DefenseReductionPotion then, as that seems like the clearest description of what the potion does. Again, thanks for the input :)

**Comment by smsunarto** [comment]
@SarahMcDougald There needs to be a code for that new potion effect. The idea of using negative multiplier can work but I don't think it's the best method since it can get pretty confusing later on. Creating a new potion effect with a reversed effect based on the `RESIST_PHYSICAL` code should be better.

**Comment by SarahMcDougald** [comment]
Okay, I've fixed the potion name and added the new effect to the PotionCommonEffects class like @smsunarto suggested. 

Are there any other changes that need to be made? I looked at a past PR for a new potion, and it didn't require any other changes besides the prefab, the icon and the edit to PotionCommonEffects. Link to that past PR:
https://github.com/Terasology/Potions/commit/b112aea10a7f195e2ea541be62baa6924e631c31

**Comment by smsunarto** [comment]
@SarahMcDougald that PR is made for Google Code-In, a competition made to introduce pre-uni student about open-source. We merged the potion, but that potion practically does nothing. A code is still necessary to make the potion effect work.

**Comment by SarahMcDougald** [comment]
Closing this pull request because it's for a new prefab that requires an entirely new alteration effect. (I will probably do a new pull request for when I make the alteration effect.)

**Pull request closed without merging**
