### PR TITLE
Added Regen II Potion & Invincible Potion

### PR DESCRIPTION
**Pull request by Minege**
Hi,

I added Regen II Potion & Invincible Potion also with the textures.

For Google CodIn 2016.

### CODE REVIEW

**Comment by Cervator** [comment]
Thanks!

Can confirm both potions can be given in-game and that the physical resist seems to work on fall damage, although not on console-based damage from the `damage` command, which is probably intentional.

The regen doesn't seem to work, but then neither does the other regen potion. I think something very recently broke a few potions so we'll figure that out. The prefab looks correct.

I'm going to assume you edited the two bottles from the base one and add that to the readme, let me know if not!

**Comment by Cervator** [comment]
Oh, also, I'm not sure if you were uploading/editing files via GitHub itself or IntelliJ? Generally with IntelliJ you can group the changes inside a single commit, which makes for cleaner revision history. Here you've got 10 commits for 5 files :-)

I'm going to merge this in with Git Rebase to cut it down to a single commit, then submit the tweak to the readme separately after another merge.

That lets you test it easily too, which I hope you did! Some PRs don't work nearly this well so I am guessing you very well may have tested, thank you if so!

**Comment by Cervator** [comment]
Closing as merged in https://github.com/Terasology/Potions/commit/66aba313f647886a1c8832b5bfa9156d7d5f72b9 (rebase breaks auto-close)

**Comment by Minege** [comment]
Hello,

Thank you :=)
I'm really happy to help !

And good luck for this game developpment ! Look like a really cool game :) 👍 

(I uploaded over github, that's why there is a lot of commits :\ )

**Pull request closed without merging**
