### PR TITLE
Updated Potion Icons + Readme

### PR DESCRIPTION
**Pull request by Trekmarvel**

### CODE REVIEW

**Comment by mdj117** [comment]
Too many commits, please make a new PR with just the final code @rzats Cleared to close at will

**Comment by smsunarto** [comment]
@mdj117 @rzats  No need to close this one. @Trekmarvel is pretty active, i've seen him several times in the forum. 

Anyway, we can just easily squashed the commit, everything is working perfectly.

**Comment by mdj117** [comment]
@Trekmarvel could you please squash the commits :-)

**Comment by rzats** [comment]
@Trekmarvel: merged, thanks for the contribution! It'd be **awesome** if you could take a look at any of the other modules with new textures: [Equipment](https://github.com/Terasology/Equipment), [SimpleFarming](https://github.com/Terasology/SimpleFarming) and [Cooking](https://github.com/Terasology/Cooking) in particular.

@mdj117: there was no need to close this. Squashing is something we can really easily do from the web interface.

**Comment by Trekmarvel** [comment]
Thanks @rzats i'll keep an eye on the other modules.

**Pull request merged**
